server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-floral-surf-aoqsfhax-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BkTDQzq8gdN7
