server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:postgresql://neondb_owner:npg_BkTDQzq8gdN7@ep-floral-surf-aoqsfhax-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${APPLICATION_USER:neondb_owner}
spring.datasource.password=${APPLICATION_PASSWORD:npg_BkTDQzq8gdN7}
